### PR TITLE
Copy button improved and few other tweaks

### PR DESCRIPTION
**Pull request by RohanTheProgrammer**
solved #355 
copy button is improved.

### CODE REVIEW

**Comment by RohanTheProgrammer** [comment]
Hi @dk3775 is it good now?

**Comment by dk3775** [comment]
It works perfect in desktop view and looks fine too, but here's the issue
See this Image!!

- Fix the button beside To Geek text.
- Also Fix or redesign twitter button.

**Comment by RohanTheProgrammer** [comment]
Should it look like galaxy S9 (both buttons side by side) or like pixel 3a xl (both buttons one over the other)

**Comment by dk3775** [comment]
I think it should look something like this
Untitled
PS: ignore my drawing but get the idea, still tell me if I am not clear enough.

**Comment by RohanTheProgrammer** [comment]
Is it necessary to put copy button above Twitter button or it can be like pixel 3a XL i.e. Twitter button above and copy button below

**Comment by dk3775** [comment]
order works fine
but layout is what I am pushing on

**Comment by RohanTheProgrammer** [comment]
Ok 👍
Got it

**Comment by dk3775** [comment]
Solved?

**Comment by RohanTheProgrammer** [comment]
@dk3775 I guess it solved pretty much everything now.
Still tell me if something left

**Comment by dk3775** [comment]
Perfect as per needed.
Still if you want to go on then fix this text box margin or tell me I will merge this PR.
Once again thanks !!

**Comment by RohanTheProgrammer** [comment]
Which text box and which side are you talking about. Can you please explain.

**Comment by Muhammed-Moinuddin** [comment]
I think maybe we should change the background color of that Twitter button. Your thoughts? & I've also edited the margin of the text area kindly check it out: https://github.com/swapagarwal/geeksay/pull/392. One thing more, I was also thinking about making the code cleaner eg, creating a separate CSS file, making JS code better, etc.

**Comment by dk3775** [comment]
Hey @RohanTheProgrammer the texbox overflow issue is fixed by #392 from @Muhammed-Moinuddin no longer need to work on it.

**Comment by RohanTheProgrammer** [comment]
oh! noice work @Muhammed-Moinuddin.
and I personally liked your suggestions

**Pull request merged**
