### PR TITLE
Improve the Mobile Responsive Version #380

### LINKED ISSUE #380: Improve the Mobile Responsive Version
Hey, I feel the mobile responsive version of the website is congested. The buttons shouldn't stick with the Geeks Output box as there's no breathable space. 
I think the buttons should be below the box. 
Also requires some minor tweaks to the responsive version.

If you Green Light this issue, can I work on it?

### PR DESCRIPTION
**Pull request by Ayush-Kanduri**
Fixes #380 

Improved the responsiveness of the website around the buttons with some minor modifications in the CSS.

Preview

### CODE REVIEW

**Comment by dk3775** [comment]
image
Works Fine!

**Review by dk3775 — APPROVED** [review]

**Comment by Ayush-Kanduri** [comment]
> image Works Fine!

Thanks Bro 😀

**Comment by Ayush-Kanduri** [comment]
Dhyey, can you please add the "hacktoberfest-accepted" label as well to it, since it has the "hacktober-accepted" label.

**Comment by dk3775** [comment]
Already added 😎😉

**Comment by Ayush-Kanduri** [comment]
> Already added 😎😉

fest is missing, will it work?

**Comment by Ayush-Kanduri** [comment]
> Ohh I completely missed it, Doing it !! Thanks for correcting.

No issues bro. Thanks 😀

**Pull request merged**
