### PR TITLE
Improve the Mobile Responsive Version & Add Social Buttons

### PR DESCRIPTION
**Pull request by Ayush-Kanduri**
Fixes the Issue #380 
I created the Issue and was assigned the same #380 

- [x] Rectified Textarea Margin + Rectified Inconsistency of Breakpoint around the buttons

## **Earlier**
Inconsistency of breakpoint around buttons

Textarea

## **Rectification**
Improve 1

- [X] Rectified Syntax Errors
Someone tweaked the file geeksay.js with syntax errors, causing the website to not run properly. I solved that very minor syntax error.

- [X] Rectified Error in URL Encode of Twitter Link
Rectified the error associated with the Twitter URL as it wasn't converting # and Space to URL Encode.

## **Earlier**
Error in URL Encode #

## **Rectification**
Improve 2

- [X] Added Social Buttons
Added Facebook & Twitter buttons below the output box. Copy button stays inline at the top of the output box. Also, improved the responsiveness a lot.

## **Final Version**
Improve 3-2

### CODE REVIEW

**Comment by Ol4bod3** [comment]
Good day sir.  am new to contributing to open source project is there anything i can work on.

**Comment by Ayush-Kanduri** [comment]
> Good day sir. am new to contributing to open source project is there anything i can work on.

Hey Olabode, you have to check out all the existing issues & work on them accordingly or you could create your own issue and then work on it.

**Comment by Ayush-Kanduri** [comment]
Hi, @dk3775 could you please review and merge the PR?

**Comment by dk3775** [comment]
Hey @Ayush-Kanduri these changes look nice but there is a small issue, you will have to fix the indention in the geeksay.js file as specified in contributing.md .

**Comment by Ayush-Kanduri** [comment]
> Hey @Ayush-Kanduri these changes look nice but there is a small issue, you will have to fix the indention in the geeksay.js file as specified in contributing.md .

Using prettier right?
Sure, I'll just do it now only.

**Comment by Ayush-Kanduri** [comment]
@dk3775 I just checked. I have already formatted geeksay.js using Prettier in this PR.

**Comment by Ayush-Kanduri** [comment]
Hi, @dk3775  I have already formatted geeksay.js using Prettier in this PR.

**Comment by dk3775** [comment]
@Ayush-Kanduri sorry for being late, still the issue persists.
image

**Comment by Ayush-Kanduri** [comment]
> @Ayush-Kanduri sorry for being late, still the issue persists.
> image
> 

So what could be done, as I already formatted it using prettier? Can you please suggest me.

**Comment by Ayush-Kanduri** [comment]
When I try to look up in the editor there's nothing new to commit as the code is already formatted and prettier is not changing it.
So not getting the change to commit.

**Comment by Ayush-Kanduri** [comment]
Still I'll try to look around what can be done. Would love your suggestion meanwhile.

**Review by Ayush-Kanduri — COMMENTED** [review]
Hey, @dk3775 I have made changes as requested. Kindly review.

**Review by dk3775 — APPROVED** [review]

**Pull request merged**
