### PR TITLE
Add "semicolon" translation

### PR DESCRIPTION
**Pull request by pavilandoangelo**

### CODE REVIEW

**Comment by pavilandoangelo** [comment]
Hi @dk3775 , added a translation. Added it also in the test file to made it sure it will pass. Let me know if there is anything I could improve. Thank you.

**Comment by dk3775** [comment]
Hey @pavilandoangelo thanks for this. You can also contribute at this issue #351

**Comment by pavilandoangelo** [comment]
Hi @dk3775 , I'll look into it. Thank you!

**Review by dk3775 — APPROVED** [review]
Looks Good!

**Comment by pavilandoangelo** [comment]
Hi @dk3775  , can you please add the label hacktoberfest-accepted? That would be mean a lot for me. I'm just starting out contributing to open source and I want to continue it with a good first experience. Thank you so much!

**Pull request merged**
