### PR TITLE
Unit test

### PR DESCRIPTION
**Pull request by pedramp**
implementing a basic `unit-test` template

## Added a few tests
* words
* quotes 
* multi-line and symbols'
* HTML tags
* different inputs 

## issue
currently, we have two commented test, related to issue #63 we should uncomment and add more after fixing this issue.

### CODE REVIEW

**Comment by pedramp** [comment]
@swapagarwal any comment?

**Comment by swapagarwal** [comment]
Looks good. Can you do consistent formatting with 4-spaces indentation?

**Comment by pedramp** [comment]
Sure 👍

**Comment by swapagarwal** [comment]
Thanks @pedramp! 👍

**Comment by swapagarwal** [comment]
Can you check the CI log here? https://travis-ci.org/swapagarwal/geeksay 😅

**Pull request merged**
