### PR TITLE
quote added

### PR DESCRIPTION
**Pull request by thekavikumar**
I have added a quote with its translations.
Do check it ✨

### CODE REVIEW

**Comment by dk3775** [comment]
@thekavikumar could you please re-do the spacing and update this pr?

**Comment by thekavikumar** [comment]
Spacing resolved!

**Comment by dk3775** [comment]
Unecessary translations!

**Comment by thekavikumar** [comment]
which one?

**Comment by dk3775** [comment]
both

**Comment by dk3775** [comment]
@thekavikumar Create a PR

**Pull request closed without merging**
