### PR TITLE
Add support for all css color aliases

### PR DESCRIPTION
**Pull request by GoosvandenBekerom**
#1 #hacktoberfest

### CODE REVIEW

**Comment by swapagarwal** [comment]
Hi, these translations are not intuitive to be used in sentences.

**Comment by GoosvandenBekerom** [comment]
I just noticed that a lot of different colors were added in the main translations object, I figured this could be its own object, while I was at it I just added all colors that have a alias.

**Comment by swapagarwal** [comment]
It's hard to decode FF7F50 as coral in a sentence, currently only easy translations are added. 😅

**Comment by GoosvandenBekerom** [comment]
Fair enough, I might have over-engineered this a bit 😂

**Pull request closed without merging**
