### PR TITLE
Added some new quotes

### PR DESCRIPTION
**Pull request by AK-codingmaniac**
Issue #5 :-
I have added some new quotes 
Please see to it and merge it as soon as possible for HacktoberFest 2022

### CODE REVIEW

**Comment by dk3775** [comment]
You have reversed the translation and quotes. I mean commented sentence should come in as string and vice versa

**Comment by AK-codingmaniac** [comment]
@dk3775 Sorry I have done the requested changes
Please see to it and merge it as soon as possible for HacktoberFest 2022

**Review by dk3775 — APPROVED** [review]

**Comment by AK-codingmaniac** [comment]
Hey @dk3775 thank you for merging my PR 
Can you please label this PR as hacktoberfest-accepted?

**Comment by AK-codingmaniac** [comment]
@dk3775 why did you invalid this PR?

**Comment by dk3775** [comment]
Ohh my bad was adding accepted but added invalid

**Pull request merged**
