### PR TITLE
Functionality to ignore symbols when translating words

### PR DESCRIPTION
**Pull request by ccoffey1**
#63 Created a regex to parse the word and remove symbols.

>Roses are red, violets are blue.
>Roses are #ff0000, violets are #0000ff.

### CODE REVIEW

**Comment by swapagarwal** [comment]
@ccoffey1 Can you take a look at the failing tests?

**Comment by ccoffey1** [comment]
Sure I'll look into it 👍

**Comment by ccoffey1** [comment]
Should be good now! @swapagarwal

**Comment by swapagarwal** [comment]
I've added some failing tests for this feature.

**Comment by ccoffey1** [comment]
Just looked at the failing tests... Not sure why those would be.... grrrrrrrr I'll have a look!

**Comment by ccoffey1** [comment]
@swapagarwal Okay! That should do it for real this time. Let me know if that's not the case lol.

**Comment by swapagarwal** [comment]
Thanks @ccoffey1 for diving into this and fixing it! 👍

**Pull request merged**
