### PR TITLE
Geek Quiz 

### PR DESCRIPTION
**Pull request by wang-ories**
# Todo : 
- Finish UI
- Implements quiz functions

### CODE REVIEW

**Comment by wang-ories** [comment]
Hello @swapagarwal, here is the first version of quiz.

**Comment by swapagarwal** [comment]
This is great! A few improvements and it'll be ready to merge.
* On submit, we should show the correct answer before advancing to the next question.
* Enter key should trigger the submit button.

**Comment by wang-ories** [comment]
> * On submit, we should show the correct answer before advancing to the next question.

Ok, I will work on theses improvements.

**Comment by dk3775** [comment]
@wang-ories Can we expect any update on this or shall we close this PR?

**Comment by Wang-onx** [comment]
@dk3775 , please you can close this PR.

**Pull request closed without merging**
