### PR TITLE
Add famous Julius Ceasar quote with Linux command line

### PR DESCRIPTION
**Pull request by chadwyck242**
Add a famous quote attributed to Julius Ceasar, but with Linux commands =)

### CODE REVIEW

**Comment by chadwyck242** [comment]
Hello @stvmachine Thank you for the feedback, I finally worked out how to edit a PR, and made the changes you suggested. I just made a new commit and pushed the changes up. Let me know if there is any further steps required, and I will get on them ASAP.

**Comment by stvmachine** [comment]
The phrase `I came, I saw, I conquered` is going to be translated as `I cd, I ls-alt, I rm -rf`.

So, do you need to add the translation:
- **,** : &&.
- **I came**: cd
- **I saw**: ls -alt
- **I conquered**: rm -rf

With that changes the phrase is going to be translated as: `cd  &&  ls -alt  &&  rm -rf`

**Comment by chadwyck242** [comment]
@stvmachine  OK, made the edits mentioned above. Maybe looks good this time? Thanks again!

**Comment by chadwyck242** [comment]
Committed the merge request, cleared the conflict markers. Thanks for looking at this!

**Comment by chadwyck242** [comment]
No activity several months

**Pull request closed without merging**
