### PR TITLE
Update geeksay.js

### PR DESCRIPTION
**Pull request by JustinXHale**
added 3 new translations

### CODE REVIEW

**Review by JustinXHale — COMMENTED** [review]
added Boobs lol

**Comment by dk3775** [comment]
The translations are not more general also you forgot the "," in the array at all the changed lines.

**Comment by dk3775** [comment]
> added Boobs lol

😐

**Comment by JustinXHale** [comment]
> > added Boobs lol
> 
> 😐

lol just an old calcuator joke 80085!

**Comment by JustinXHale** [comment]
> 

what does more general mean, sorry?

**Comment by dk3775** [comment]
It means that the translations you've just added except the last one are specific like only used in your given quotes. We need translations for words that are more often used. Still, tell me if I am not clear enough.

**Review by JustinXHale — COMMENTED** [review]
removed less general, added new quotes.

**Comment by JustinXHale** [comment]
> It means that the translations you've just added except the last one are specific like only used in your given quotes. We need translations for words that are more often used. Still, tell me if I am not clear enough.

i think i understand. thank you for the feedback. i've made some changes

**Pull request merged**
