### PR TITLE
Added Geek Background and micro interactions

### PR DESCRIPTION
**Pull request by saviomartin**
@swapagarwal 
## Hi bro,
I have made some really cool updation to your awesome project. **geeksay**
**This is how it looks likes now.** 😉

This is how it looks now

**I hope you loved it**

## What all things I have developed in this **Pull Request**
 - Changed the background to a SVG background.
	 Geeks love dark mode. So I put a code-styled background.
	 
 - Fixed some responsive problems of buttons.
 Now it is fully responsive on all devices.
 
- Add some cool box-shadow.
 Now it looks like a pro.

- Added some nice fonts.
	There were no fonts in the textarea. So I added some to make it good

- Followed a colour pattern.
	Following a color, pattern is an important thing in making cool sites.

- **Tested many times. NO issues. Works perfect.**

- Only made updation in `index.html`.

Thank you, 😊 
[Savio Martin](https://github.com/saviomartin)

### CODE REVIEW

**Comment by dk3775** [comment]
@saviomartin Preview is not visible could you please reshare the Screenshot of new preview?

**Comment by dk3775** [comment]
image

@swapagarwal this changes made by @saviomartin looks really great!!
Its Ready to be merged!!

**Comment by swapagarwal** [comment]
good to go

**Comment by dk3775** [comment]
I am closing this PR fixing some merge issues and addind this code via new PR.

**Pull request closed without merging**
