### PR TITLE
Fixed issue #63, now punctuation is not considered part of the word.

### PR DESCRIPTION
**Pull request by AdnCodez**
I have used regular expression in this, you can modify the character that are not considered part of the word :)

### CODE REVIEW

**Comment by swapagarwal** [comment]
The output does not match the one mentioned in the issue description: https://deploy-preview-66--optimistic-volhard-494237.netlify.com/

**Comment by AdnCodez** [comment]
Oh I see, I'll try to fix it asap :)

**Comment by AdnCodez** [comment]
I have added another solution to the punctuation issue, which solves the problem that you mentioned, I didn't use regex, I have only included the ',' and '.' (comma, and period), I would like to hear from you about this solution 🙂

**Comment by swapagarwal** [comment]
This solution is not extensible wrt more symbols.

**Pull request closed without merging**
