### PR TITLE
Added dark theme version.

### LINKED ISSUE #51: Dark Mode
Isn't it a good idea to add dark mode to the site because who doesn't use dark mode?

### PR DESCRIPTION
**Pull request by mbledkowski**
Fixes #51

### CODE REVIEW

**Comment by mmacq** [comment]
Dark themed version is in separate file "dark-theme.html"

**Comment by swapagarwal** [comment]
Looks great! Can you integrate this with a toggle on the main page?

**Comment by mmble** [comment]
@swapagarwal Hi, I made necessary changes ;)

**Comment by mmble** [comment]
@swapagarwal So what is the decision?

**Comment by swapagarwal** [comment]
Looks good. There are some formatting changes as well. Can you make them first in a separate PR to make it easy to review?

**Pull request closed without merging**
