### PR TITLE
Added New Quotes(#336)

### PR DESCRIPTION
**Pull request by AK-codingmaniac**

### CODE REVIEW

**Comment by AK-codingmaniac** [comment]
Please see to it and merge it as soon as possible for HacktoberFest 2022

**Review by dk3775 — APPROVED** [review]

**Comment by dk3775** [comment]
@AK-codingmaniac your additions to translations and quotes are valid but the code is formatted after your PR, so you can update your PR. Remember to use Prettier for formatting the code.

**Review by dk3775 — CHANGES_REQUESTED** [review]
Reformat the code using Prettier.

**Comment by AK-codingmaniac** [comment]
I have committed the requested changes

**Comment by dk3775** [comment]
Still the issue persists,
image

I guess you are using 3 spaces you need to use tabs.

**Comment by AK-codingmaniac** [comment]
\I can't understand what I was doing wrong.
@dk3775 can you tell me exactly what I have to do?

**Comment by AK-codingmaniac** [comment]
I have contributed to this repo in the past but that time it doesn't give any error 
this time I don't know what was wrong I am doing

**Comment by dk3775** [comment]
@AK-codingmaniac I think that while formatting you are using 3 spaces for formatting but instead use 4 spaces for indention.

**Comment by AK-codingmaniac** [comment]
> @AK-codingmaniac I think that while formatting you are using 3 spaces for formatting but instead use 4 spaces for indention.

At which line no.?

**Comment by dk3775** [comment]
inside the all {},[].

**Comment by AK-codingmaniac** [comment]
Now can you check it @dk3775?

**Comment by dk3775** [comment]
@AK-codingmaniac noe finally the sapcing is proper but you hav removed all '""'
image
 😐

**Comment by AK-codingmaniac** [comment]
Ok wait I will do that
Sorry

**Comment by AK-codingmaniac** [comment]
But in the codebase there were no " " in words section

**Comment by AK-codingmaniac** [comment]
Again I have done the changes 
Please see to it

**Review by dk3775 — CHANGES_REQUESTED** [review]
Now it looks good, still changes on line 128-131 are unnecessary except ";". also the changes on line 169 and 168.

**Comment by AK-codingmaniac** [comment]
@dk3775 now take a look

**Review by dk3775 — CHANGES_REQUESTED** [review]
Addition on line 221 is throwing error.
image

Also please ignore changes below line 183 it will break the functionalities.

**Comment by AK-codingmaniac** [comment]
@dk3775 I can't understand it

**Comment by dk3775** [comment]
You can do one thing just copy your translations, then delete your fork and create new fork and then just the translations. And thus create new PR.

**Pull request closed without merging**
